PrankAWSWebApp/Areas/Admin/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Prank.Model;
using PrankAWSWebApp.Areas.Admin.Models;
using PrankAWSWebApp.Controllers;
using PrankAWSWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using PrankAWSWebApp.Utility;
using PrankAWSWebApp.Factory;
using Microsoft.AspNetCore.Identity;
using PrankAWSWebApp.Areas.Admin.Data;
using Microsoft.Extensions.Configuration;
using System.Security.Claims;
using PrankAWSWebApp.Common;
using Newtonsoft.Json;

namespace PrankAWSWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    public class PackageController : Controller
    {
        IConfiguration _iconfiguration;
        private readonly IOptions<MySettingsModel> appSettings;
        private readonly SignInManager<PrankIdentityUser> loginManager;
        private readonly UserManager<PrankIdentityUser> userManager;
        private Task<PrankIdentityUser> GetCurrentUserAsync() => userManager.GetUserAsync(HttpContext.User);

        public string EmployeeId { 
            get {
                //var usr = await GetCurrentUserAsync();
                var task = Task.Run(async () => await GetCurrentUserAsync());
                return task.Result.Id;
                //return usr?.Id;
            }
        }
        public PackageController(IOptions<MySettingsModel> app, SignInManager<PrankIdentityUser> loginManager, IConfiguration iconfiguration, UserManager<PrankIdentityUser> userManager)
        {
            appSettings = app;
            ApplicationSettings.WebApiUrl = appSettings.Value.WebApiBaseUrl;
            this.loginManager = loginManager;
            this.userManager = userManager;
            _iconfiguration = iconfiguration;


        }
        // GET: PackageController
        public async Task<IActionResult> Index()
        {
            return View();
        }



        // GET: PackageController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PackageController/Create
        public ActionResult Create()
        {
            return View();
        }

        //public async Task<IActionResult> PartialGetPackages()
        //{
        //    string token = string.Empty;
        //    var claimsIdentity = (ClaimsIdentity)HttpContext.User.Identity;
        //    var userTokenClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == "Token");
        //    if (userTokenClaim != null)
        //    {
        //        token = userTokenClaim.Value;
        //    }


        //    var data = await ApiClientFactory.Instance.GetPackages(token);

        //    string viewFromCurrentController = await this.RenderViewToStringAsync("PartialGetPackages", data);

        //    return Json(
        //       new
        //       {
        //           html = viewFromCurrentController
        //       });
        //}

        public async Task<IActionResult> PartialGetPackages(int iDisplayLength, int iDisplayStart, int iSortCol_0, string sSortDir_0)
        {
            string token = string.Empty;
            var claimsIdentity = (ClaimsIdentity)HttpContext.User.Identity;
            var userTokenClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == "Token");
            if (userTokenClaim != null)
            {
                token = userTokenClaim.Value;
            }
            try
            {
                string sortCol = string.Empty;
                switch (iSortCol_0)
                {

                    case 0:
                        {
                            sortCol = "PackageTitle";
                            break;
                        }
                    case 1:
                        {
                            sortCol = "TokenCreditsPoint";
                            break;
                        }
                    case 2:
                        {
                            sortCol = "PackagePrice";
                            break;
                        }
                    default:
                        {
                            sortCol = "PackageId";
                            break;
                        }
                }
                var filter = new FilterModel()
                {
                    Token = token,
                    Skip = iDisplayStart,
                    Take = iDisplayLength,
                   // Search = sSearch,
                    SortCol = sortCol,
                    SortDir = sSortDir_0
                };
                var data = await ApiClientFactory.Instance.GetPackages(filter);

                if (data.responseObject != null)
                {
                   // var data = JsonConvert.DeserializeObject<List<PackagesModelViewModel>>(result.responseObject.ToString());

                    var results = new
                    {
                        iTotalRecords = data.responseObject.Any() ? data.responseObject.FirstOrDefault().TotalCount : 0,
                        iTotalDisplayRecords = data.responseObject.Any() ? data.responseObject.FirstOrDefault().TotalCount : 0,
                        aaData = data.responseObject
                    };
                    return Json(results);
                }
            }
            catch (Exception e)
            {
                throw;
            }
            return Json(new { });
        }

        public async Task<IActionResult> PartialCreate()
        {
            var model = new PackagesModelViewModel();
            //string viewFromAnotherController = await this.RenderViewToStringAsync("/Views/News/_NewsList.cshtml", newsItem);
            string viewFromCurrentController = await this.RenderViewToStringAsync("PartialCreate", model);

            return Json(
               new
               {
                   html = viewFromCurrentController
               });
        }
        public async Task<IActionResult> PartialEdit(int id)
        {
            string viewFromCurrentController = "";
            var model = new PackagesModelViewModel();
            try
            {
                string token = string.Empty;
                var claimsIdentity = (ClaimsIdentity)HttpContext.User.Identity;
                var userTokenClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == "Token");
                if (userTokenClaim != null)
                {
                    token = userTokenClaim.Value;
                }
                model = await ApiClientFactory.Instance.GetPackageById(token, id);
                viewFromCurrentController = await this.RenderViewToStringAsync("PartialEdit", model);
            }
            catch(Exception ex)
            {
                string ss = ex.ToString();
            }
            return Json(
               new
               {
                   html = viewFromCurrentController
               });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> SaveUpdate(PackagesModelViewModel packagesModel)
        {
            var data = new PackagesDataModel();
            var objResponse = new SaveResponse();
            string viewFromCurrentController = string.Empty;
            List<string> lstString = new List<string>
                    {
                        string.Empty
                    };
            if (ModelState.IsValid)
            {
                try
                {
                    string token = string.Empty;
                    var claimsIdentity = (ClaimsIdentity)HttpContext.User.Identity;
                    var userTokenClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == "Token");
                    if (userTokenClaim != null)
                    {
                        token = userTokenClaim.Value;
                    }
                    var model = new PackagesModel()
                    {
                        AddedDate = DateTime.UtcNow,// Convert.ToDateTime("2020-06-19T18:44:40.633Z"),
                        IsActive = packagesModel.IsActive,
                        ModifiedDate = DateTime.UtcNow,// Convert.ToDateTime("2020-06-19T18:44:40.633Z"),
                        PackageId = packagesModel.PackageId,
                        PackagePrice = packagesModel.PackagePrice,
                        PackageTitle = packagesModel.PackageTitle,
                        ProductIdentifier = packagesModel.ProductIdentifier,
                        SortOrder = packagesModel.SortOrder,
                        TokenCreditsPoint = packagesModel.TokenCreditsPoint
                    };
                    if (model.PackageId > 0)
                    {
                        data = await ApiClientFactory.Instance.UpdatePackages(token, model);
                        
                    }
                    else
                    {
                        data = await ApiClientFactory.Instance.SavePackages(token, model);
                       
                    }

                   

                    if (data.responseObject != null && data.responseObject.Any())
                    {
                        viewFromCurrentController = await this.RenderViewToStringAsync("PartialGetPackages", data.responseObject);
                    }
                    objResponse.StatusCode = Convert.ToInt32(data.statusCode);
                    objResponse.Html = viewFromCurrentController;
                    if (Convert.ToInt32(data.statusCode)==200)
                    {
                        objResponse.Message="Record saved successfully";
                        await TrackingInfo.TrackInfo(token, EmployeeId, ControllerContext.ActionDescriptor.ControllerName, model.PackageTitle,
                            model.PackageId, model.PackageId>0?"Update":"Save");
                    }
                    else
                    {

PrankAWSWebApp/Areas/Admin/Views/Package/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .containerNew {
        max-width: 80%;
        width: 100%;
        margin: 0 auto;
    }
</style>
<div class="containerNew">
    <div class="row">
        <div class="col text-left">
            <h2>Manage Package</h2>
        </div>
        <div class="col text-right">
            <button class="btn bg-facebook border" id="btnAddPackage">Add</button>
        </div>
        <div class="col-md-12 mt-4  table-responsive">
            <table class="table table-bordered table-hover" id="dataTablePackageinfo">
                <thead class="thead-light ">
                    <tr>

                        <th scope="col">PackageTitle </th>
                        <th scope="col">TokenCreditsPoint</th>
                        <th scope="col">PackagePrice</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="myPackageModal" role="dialog">
    <div class="modal-dialog modal-custom">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="packageHeading">Add/Edit Package</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div id="dvaddPackage"></div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default btn-primary pull-right" id="btnSave"> Save</button>
                <button type="button" class="btn btn-default btn-default pull-right" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Close</button>

            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/Packages/packages-main.js"></script>

@*<script src="~/js/jquery-ui.min.js"></script>
<script src="~/DataTable/jquery.dataTables.min.js" type="text/javascript"></script>*@

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

PrankAWSWebApp/Areas/Admin/Views/Package/PartialCreate.cshtml
@model PrankAWSWebApp.Models.PackagesModelViewModel

<form asp-controller="Package" asp-action="SaveUpdate" id="frmpackage">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group row">
        <label class="col-md-4">Title</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.PackageTitle, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PackageTitle, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group row">
        <label class="col-md-4">Price</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.PackagePrice, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PackagePrice, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4">Token Credit Point</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.TokenCreditsPoint, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TokenCreditsPoint, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4">Sort Order</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.SortOrder, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SortOrder, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4">Product Identifier</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.ProductIdentifier, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ProductIdentifier, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row text-left">
        <label class="col-md-4">&nbsp;</label>
        <div class="col-md-8">
            Active @Html.CheckBoxFor(p => p.IsActive)
        </div>
    </div>

</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

PrankAWSWebApp/Areas/Admin/Views/Package/PartialEdit.cshtml
@model PrankAWSWebApp.Models.PackagesModelViewModel

<form asp-controller="Package" asp-action="SaveUpdate" id="frmpackage" class="form-horizontal">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class=" form-group row">
        <label class="col-md-4">Title</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.PackageTitle, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PackageTitle, "", new { @class = "text-danger" })
            @Html.HiddenFor(p => p.PackageId)
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4">Price</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.PackagePrice, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PackagePrice, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4">Token Credit Point</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.TokenCreditsPoint, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TokenCreditsPoint, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4">Sort Order</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.SortOrder, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SortOrder, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4">Product Identifier</label>
        <div class="col-md-8">
            @Html.TextBoxFor(p => p.ProductIdentifier, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ProductIdentifier, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row text-left">
        <label class="col-md-4">&nbsp;</label>
        <div class="col-md-8">
            Active @Html.CheckBoxFor(p => p.IsActive)
        </div>
    </div>

</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>