PrankAWSWebApp/Areas/Admin/Controllers/PrankController.cs
using System;
using System.Linq;
using Microsoft.Extensions.Options;
using PrankAWSWebApp.Utility;
using PrankAWSWebApp.Factory;
using Microsoft.AspNetCore.Identity;
using PrankAWSWebApp.Areas.Admin.Data;
using Microsoft.Extensions.Configuration;
using PrankAWSWebApp.Common;
using Microsoft.AspNetCore.Mvc;
using PrankAWSWebApp.Models;
using System.Threading.Tasks;
using System.Security.Claims;
using PrankAWSWebApp.Areas.Admin.Models;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Prank.Model;
using Amazon.S3.Transfer;
using Amazon.S3;
using Amazon;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using PrankAWSWebApp.AwsS3;
using Microsoft.AspNetCore.Authorization;

namespace PrankAWSWebApp.Areas.Admin.Controllers
{
  [Authorize]
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    public class PrankController : Controller
    {
        IConfiguration _iconfiguration;
        private readonly IOptions<MySettingsModel> appSettings;
        private readonly SignInManager<PrankIdentityUser> loginManager;
        private readonly UserManager<PrankIdentityUser> userManager;
        private readonly IHostingEnvironment hostEnvironment;

        private Task<PrankIdentityUser> GetCurrentUserAsync() => userManager.GetUserAsync(HttpContext.User);
        public string EmployeeId
        {
            get
            {
                var task = Task.Run(async () => await GetCurrentUserAsync());
                return task.Result.Id;
            }
        }

        private readonly IAwsS3HelperService _awsS3Service;

        private AmazonS3Client _s3Client = new AmazonS3Client(RegionEndpoint.APSouth1);
        private string _bucketName = "prankapibucket";// "mis-pdf-library";//this is my Amazon Bucket name
        private static string _bucketSubdirectory = "Images";// String.Empty;



        private const string filePath = null;
        // Specify your bucket region (an example region is shown).  
        private static readonly string bucketName = "prankapibucket";
        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.APSouth1;
        private static readonly string accesskey = "AKIAWAXVQOY4K5MNJGGH";
        private static readonly string secretkey = "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";


        public PrankController(IHostingEnvironment environment, IOptions<MySettingsModel> app, SignInManager<PrankIdentityUser> loginManager, IConfiguration iconfiguration, UserManager<PrankIdentityUser> userManager, IAwsS3HelperService awsS3Service)
        {
            appSettings = app;
            ApplicationSettings.WebApiUrl = appSettings.Value.WebApiBaseUrl;
            this.loginManager = loginManager;
            this.userManager = userManager;
            _iconfiguration = iconfiguration;
            hostEnvironment = environment;
            _awsS3Service = awsS3Service;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PartialPrankInfoLst(int iDisplayLength, int iDisplayStart, int iSortCol_0, string sSortDir_0, string sSearch)
        {
            string token = string.Empty;
            var claimsIdentity = (ClaimsIdentity)HttpContext.User.Identity;
            var userTokenClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == "Token");
            if (userTokenClaim != null)
            {
                token = userTokenClaim.Value;
            }
            try
            {
                string sortCol = string.Empty;
                switch (iSortCol_0)
                {

                    case 0:
                        {
                            sortCol = "PrankName";
                            break;
                        }
                    case 1:
                        {
                            sortCol = "PrankDesc";
                            break;
                        }
                    case 2:
                        {
                            sortCol = "IsActive";
                            break;
                        }
                    case 3:
                        {
                            sortCol = "AddedDate";
                            break;
                        }
                    case 4:
                        {
                            sortCol = "ModifiedDate";
                            break;
                        }

                    default:
                        {
                            sortCol = "PrankId";
                            break;
                        }
                }
                var data = await ApiClientFactory.Instance.GetPrankInfo(token, iDisplayStart, iDisplayLength, sSearch, sortCol, sSortDir_0);
                
                var result = new
                {
                    iTotalRecords = data.Any() ? data.FirstOrDefault().TotalCount : 0,
                    iTotalDisplayRecords = data.Any() ? data.FirstOrDefault().TotalCount : 0,
                    aaData = data
                };
                return Json(result);
            }
            catch (Exception e)
            {
                throw;
            }
        }
 
        public async Task<IActionResult> PartialAddEditPrankInfo(int prankId)
        {
            var model = new PrankAddEditModel();
            if (prankId > 0)
            {
                try
                {
                    string token = string.Empty;
                    var claimsIdentity = (ClaimsIdentity)HttpContext.User.Identity;
                    var userTokenClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == "Token");
                    if (userTokenClaim != null)
                    {
                        token = userTokenClaim.Value;
                    }
                    var result = await ApiClientFactory.Instance.GetPrankInfoById(token, prankId);
                    if (result != null & result.Count > 0)
                    {
                        foreach (var item in result)
                        {
                            model.PrankId = item.PrankId;
                            model.PrankName = item.PrankName;
                            model.PrankDesc = item.PrankDesc;
                            model.PrankImage = item.PrankImage;
                            model.PreviewAudioFile = item.PreviewAudioFile;
                            model.MainAudioFile = item.MainAudioFile;
                            model.PlivoAudioXmlUrl = item.PlivoAudioXmlUrl;
                            model.IsActive = item.IsActive;
                            model.AddedDate = item.AddedDate;
                        }
                    }
                }
                catch (Exception e)
                {
                }
            }
            string viewFromCurrentController = await this.RenderViewToStringAsync("PartialAddEditPrankInfo", model);
            return Json(new { html = viewFromCurrentController });
        }

        public ActionResult SavePrankImageRequest()
        {
            bool isCorrectFile = false;
            var StrMessage = SaveImage(ref isCorrectFile);
            return Json(new { response = StrMessage, isSuccess = isCorrectFile });
        }
        public ActionResult SavePrankAudioRequest()
        {
            bool isCorrectFile = false;
            var StrMessage = SaveAudio(ref isCorrectFile);
            return Json(new { response = StrMessage, isSuccess = isCorrectFile });
        }

        public async Task<bool> uploadToBucket(IFormFile file)
        {
            var fileName = ContentDispositionHeaderValue
               .Parse(file.ContentDisposition)
               .FileName
               .TrimStart().ToString();
            var folderName = "Images";// Request.Form.ContainsKey("folder") ? Request.Form["folder"].ToString() : null;
            bool status = false;
            using (var fileStream = file.OpenReadStream())
                try
                {
                    using (var ms = new MemoryStream())
                    {
                        await fileStream.CopyToAsync(ms);
                        status = await _awsS3Service.UploadFileAsync(ms, fileName, folderName);
                    }
                }
                catch (Exception ex)
                {
                    string str = ex.ToString();
                }
            return status;
        }
        public void uploadToS3(string filePath)
        {
            try
            {
                TransferUtility fileTransferUtility = new
                    TransferUtility(new AmazonS3Client(Amazon.RegionEndpoint.APSouth1));

                string bucketName;


                if (_bucketSubdirectory == "" || _bucketSubdirectory == null)
                {
                    bucketName = _bucketName; //no subdirectory just bucket name  
                }
                else
                {   // subdirectory and bucket name  
                    bucketName = _bucketName + @"/" + _bucketSubdirectory;
                }


                // 1. Upload a file, file name is used as the object key name.
                fileTransferUtility.Upload(filePath, bucketName);
                Console.WriteLine("Upload 1 completed");


            }
            catch (Exception ex)
            {
                string str = ex.ToString();
            }
            //catch (AmazonS3Exception s3Exception)
            //{
            //    Console.WriteLine(s3Exception.Message,
            //                      s3Exception.InnerException);
            //}
        }

        public bool sendMyFileToS3(System.IO.Stream localFilePath, string bucketName, string subDirectoryInBucket, string fileNameInS3)
        {
            //IAmazonS3 client = new AmazonS3Client(RegionEndpoint.APSouth1);
            try
            {
                IAmazonS3 client = new AmazonS3Client(accesskey, secretkey, bucketRegion);

PrankAWSWebApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title </title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/toastr/toastr.css" rel="stylesheet" />

    <script type="text/javascript" src="~/lib/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/lib/toastr/toastr.min.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <link href="~/lib/datatable/dataTables.bootstrap4.min.css" rel="stylesheet" />

</head>
<body>
    <div class="loadingBox" style="display:none;">
        <div class="loadingImg">
            <img src="~/Images/Loader.gif" />
        </div>
    </div>
    <header class="bg-white shadow-sm">
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-facebook border-bottom box-shadow mb-3">*@
        <nav class="navbar navbar-expand-lg bg-facebook navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand " asp-controller="Movies" asp-action="Index"> <b> Dagga </b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex flex-lg-row-reverse">

                    <ul class="navbar-nav text-white flex-grow-1">
                        <li class="mr-auto"></li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home @User.Claims.FirstOrDefault(c => c.Type == "UserName")</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Prank" asp-action="Index">Pranks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Package" asp-action="Index">Packages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="ReferralInfo" asp-action="Index">Referral </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="ReferralInviteInfo" asp-action="Index">Referral Invites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="PageContent" asp-action="Index">Term & Conditions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="DeviceInfo" asp-action="Index">Devices</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="CallTracking" asp-action="Index">Call Tracking</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
                        </li>
                        @if (User.IsInRole(PrankAWSWebApp.Common.Constants.UserRoles.SuperAdmin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Employee" asp-action="Index">Employee</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="PrankCallFromPhoneNumber" asp-action="Index">Manage From Numbers</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Account
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (User.IsInRole(PrankAWSWebApp.Common.Constants.UserRoles.SuperAdmin))
                                {
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="TrackingInfo" asp-action="Index">Tracking Info</a>
                                }
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Account" asp-action="LogOff">Logout</a>

                            </div>
                        </li>

                    </ul>

                </div>

                @*<a class="btn btn-light nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Add</a>*@
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <!-- Button trigger modal -->
    <!-- Modal -->
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@


    @*@RenderSection("Scripts", required: false)*@
    <script src="https://momentjs.com/downloads/moment.js"></script>
    @*<script src="~/lib/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="~/lib/datatable/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatable/dataTables.bootstrap4.min.js"></script>

</body>
</html>